source 'http://rubygems.org'
#source 'http://ruby.taobao.com'

gem 'rails', '3.1.1'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'               , '1.3.6'
gem "mongrel"               , '1.2.0.pre2'
gem "cgi_multipart_eof_fix" ,'2.5.0'
gem "fastthread"            ,'1.0.7'
gem "nifty-generators"      ,'0.4.6'
gem 'will_paginate'         , '~> 3.0.pre2'
gem 'debugger'
gem 'diff-lcs'


group :test do
  gem 'cucumber-rails'     ,'1.3.0', :require => false
  gem 'database_cleaner'   ,'0.9.1'
end

group :development,:test do
  gem 'rspec-rails'        ,'2.13.2'
  gem 'faker'              ,'1.1.2'
  gem 'factory_girl_rails' ,'4.1.0'
  gem 'spork'              ,'1.0.0rc3'
  gem 'spork-rails'        ,'3.2.0'
  gem 'guard'              ,'1.5.2'
  gem 'guard-spork'        ,'1.2.2'
  gem 'guard-rspec'        ,'2.1.1'
  gem 'rspec'              ,'2.13.0'
  gem 'guard-test'         ,'0.5.0'
  gem 'test-unit'          ,'2.5.2', :require => false
  gem 'spork-testunit'     ,'0.0.8'
  gem 'listen'             ,'0.5.3'

  gem 'cucumber'
  gem 'guard-cucumber'
  gem 'capybara'
  gem 'guard-livereload'

#  gem 'guard-pow'

  gem 'growl',                      :require => false if RUBY_PLATFORM =~ /darwin/i
  gem 'rb-fsevent'         ,'0.9.1',:require => false if RUBY_PLATFORM =~ /darwin/i

  gem 'rb-inotify'         ,'0.8.8' if RUBY_PLATFORM =~ /linux/i


  
  #  gem 'ruby-debug19'
end


#group :linux do
#  gem 'rb-inotify', '0.8.8'
#end
# Use unicorn as the web server
# gem 'unicorn'



# Deploy with Capistrano
# gem 'capistrano'




# To use debugger
# gem 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
